name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: check file
      id: check-file
      uses: education/autograding-command-grader@v1
      with:
        test-name: check file
        setup-command: ''
        command: "[ -f info.txt ]"
        timeout: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        CHECK-FILE_RESULTS: "${{steps.check-file.outputs.result}}"
      with:
        runners: check-file
